### ISSUE TITLE
[feat] 리뷰 리스트 및 리뷰 삭제

### ISSUE THREAD

**Issue by Judy-999** [Judy-999/ios-wanted-BoxOffice#17]
## Description
리뷰 리스트

## Todo
- [x] 리뷰 리스트 레이아웃 정리
- [x] Firestore 리뷰 저장 collection 변경 (영화 제목+연도)
- [x] 리뷰 삭제 기능
- [x] 리뷰 리스트 화면
