### ISSUE TITLE
[feat] Firebase 및 FireStorage 매니저 구현

### ISSUE THREAD

**Issue by Judy-999** [Judy-999/ios-wanted-BoxOffice#3]
## Description
Firebase 및 FireStorage 사용을 연결해줄 Manager 객체 구현

## Todo
- [x] Firebase 프로젝트 연결
- [x] Firebase의 CURD 구현
- [x] FireStorage의 CURD 구현
- [x] FirebaseUsecase 구현
