### ISSUE TITLE
[feat] 홈화면 구현

### ISSUE THREAD

**Issue by wongbingg** [Judy-999/ios-wanted-BoxOffice#6]
## Description
일별 박스오피스 목록을 보여주는 화면 구현
@Judy-999 와 Figma를 통해 만들었던 프로토타입을 기준으로 UI 구성

|홈 화면|보기변경 탭시|
|:---:|:---:|
|<img width="200" alt="스크린샷 2023-01-03 오전 10 46 30" src="https://user-images.githubusercontent.com/95671495/210290618-1bf453c4-68f9-44ec-956e-2ea3d5529366.png">|<img width="200" alt="스크린샷 2023-01-03 오전 10 46 44" src="https://user-images.githubusercontent.com/95671495/210290628-300f5ebb-f408-4656-9ad3-7716ac0719e9.png">|
|`CollectionView`,`DiffableDataSource`|`InputView`,`etc`|

## Todo
- [x] UICollectionViewCell 생성
- [x] UICollectionView 생성
- [x] UICollectionViewCompositionalLayout 생성
- [x] UICollectionViewDiffableDataSource 생성
- [x] ViewModel 생성
- [x] 보기변경 버튼 생성
- [x] 보기변경 버튼 탭시, 아래에서 위로 올라오는 모달뷰 생성
- [x] 우측상단 달력버튼 생성
- [x] 달력버튼 탭시, 데이트피커 모달뷰 생성
- [x] 보기변경 항목[일별, 주중/주간] 으로 layout 변경 가능성 열어두기
